#! /bin/bash

g++ -g -L ~/lib -I ../ -l TopTreeAnaContent53 -l TopTreeAna53 -l MLP -l TreePlayer -l TMVA -l XMLIO -I `root-config --incdir` `root-config --libs` FourTop_EventSelection_Run2.cc -o MACRO
