print "        #                        # # # #                                   "
print "  (.)   #  #                  #           #====================            "
print "        #    #    (.)      #                 #                 \\    (.)   "
print "        #      #        #                       #               \\         "
print "        #        # #                      ((.)) __\              \\        "
print "        #        # #                              /              ***       "
print "        #      #     #                            #             **+**      "
print "        #    #          # ***TEAM DEVIL FISH*** #                ***       "
print "        #  #               #                 #        (.)                  "
print "        #    (.)              #           #                                "
print "                                 # # # #                                   "
