print "        #                     #  # # #                                   "
print "  (.)   #  #                #           #====================            "
print "        #    #    (.)    #                 #                 \\    (.)   "
print "        #      #      #                         #               \\         "
print "        #        # #                      ((.))   #              \\        "
print "        #        # #                             /               ***       "
print "        #      #      #                          /               **+**      "
print "        #    #          # ***TEAM DEVIL FISH    \                ***       "
print "        #  #               #                     \     (.)                 "
print "        #    (.)                               #                          "
print "                                #              #                           "
print "                                  # # # #                                  "
